[package]
name = "using_demo_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
metacontrols-server = { path = "../../../server" }
egui_demo_lib = { path = "../../../../egui/crates/egui_demo_lib" }
