[package]
name = "metacontrols-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tungstenite = "*"
tokio = { version = "1", features = ["rt", "net", "sync"] }
log = "0.4.21"
futures-util = "0.3.30"
metacontrols-common = { path = "../common" }
bincode = "1.3.3"
