[package]
name = "metacontrols-server"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.27.2"
tokio-tungstenite = "*"
tokio = { version = "1", features = ["rt", "net", "sync"] }
log = "0.4.21"
futures-util = "0.3.30"
